import type { DivergenceAnalysis, DivergenceReasonCategory, Guideline } from "@/lib/types";

/**
 * Structured "why do these guidelines diverge" breakdown for an Ask answer
 * that cites two or more guidelines disagreeing on the same question.
 * Modeled on the chronic-pain RecMap protocol's defined divergence-
 * exploration method: rather than only noting that guidelines disagree,
 * trace WHY — differing evidence cutoffs, differing values placed on
 * benefits vs. harms, population/subgroup differences, or differences in
 * process rigor / evidence certainty. Every reason is generated by the
 * same LLM call that answers the question, grounded in the cited
 * guidelines' catalog data (see lib/chatPrompt.ts) — this only renders
 * when the model actually flagged real divergence, never fabricated.
 *
 * Presented as amber cards, per the v3 snapshot. Amber rather than red is
 * the right register: divergence between guidelines is a thing to look at
 * carefully, not an error — two panels can read the same evidence and
 * land differently for defensible reasons.
 */

/** One icon per divergence category, so a reader can tell at a glance
 *  whether two guidelines split over the evidence, over values, or over
 *  who the recommendation is for. */
const CATEGORY_ICONS: Record<DivergenceReasonCategory, React.ReactNode> = {
  evidence_cutoff: <path d="M4.5 5h15l-5.8 6.8v5.4l-3.4 2.3v-7.7Z" />,
  values_and_preferences: (
    <>
      <path d="M12 6.5v13M5 10h14" />
      <path d="M5 10 2.8 15a2.4 2.4 0 0 0 4.4 0Z" />
      <path d="M19 10l-2.2 5a2.4 2.4 0 0 0 4.4 0Z" />
    </>
  ),
  population_differences: (
    <>
      <path d="M9 11.2a2.9 2.9 0 1 0 0-5.8 2.9 2.9 0 0 0 0 5.8Z" />
      <path d="M3.6 19.2a5.4 5.4 0 0 1 10.8 0" />
      <path d="M16 6.1a2.9 2.9 0 0 1 0 5.4M17.4 14.6a5.4 5.4 0 0 1 3 4.6" />
    </>
  ),
  rigor_of_process: (
    <>
      <path d="M8 4.5H6.6A1.6 1.6 0 0 0 5 6.1v13.3a1.6 1.6 0 0 0 1.6 1.6h10.8a1.6 1.6 0 0 0 1.6-1.6V6.1a1.6 1.6 0 0 0-1.6-1.6H16" />
      <path d="M9.4 3h5.2v3H9.4Z" />
      <path d="m8.8 12 2 2 4-4.2" />
    </>
  ),
  certainty_of_evidence: (
    <>
      <path d="M12 3.2 5.6 5.8v5.5c0 4 2.7 7.2 6.4 8.5 3.7-1.3 6.4-4.5 6.4-8.5V5.8Z" />
      <path d="m9.3 12 2 2 3.5-3.7" />
    </>
  ),
  other: (
    <>
      <path d="M12 20.6a8.6 8.6 0 1 0 0-17.2 8.6 8.6 0 0 0 0 17.2Z" />
      <path d="M12 11.2v5M12 8.1v.4" />
    </>
  ),
};

/** Each cited guideline keeps one colour for the whole panel, so "NICE" is
 *  the same chip in every reason. Assigned by first appearance rather than
 *  hashed, so the palette stays legible however many sources there are. */
const SOURCE_TONES = ["teal", "blue", "violet", "green", "rose", "slate"] as const;

export default function DivergencePanel({
  divergence,
  guidelineById,
}: {
  divergence: DivergenceAnalysis;
  guidelineById: (id: string) => Guideline | undefined;
}) {
  if (!divergence.hasDivergence || divergence.reasons.length === 0) return null;

  const toneById = new Map<string, string>();
  for (const reason of divergence.reasons) {
    for (const id of reason.guidelineIds) {
      if (!toneById.has(id)) toneById.set(id, SOURCE_TONES[toneById.size % SOURCE_TONES.length]);
    }
  }

  return (
    <>
      <section className="divergence-panel">
        <h2 className="divergence-h">
          Why these guidelines diverge
          <span
            className="divergence-info"
            title="Guidelines can disagree for defensible reasons — a different evidence cutoff, a different weighting of benefits against harms, or a different target population. These are the reasons RecMap could trace from the cited guidelines' own data."
            aria-label="How to read this section"
            role="img"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">
              <circle cx="12" cy="12" r="9" />
              <path d="M12 11v5.4" strokeLinecap="round" />
              <path d="M12 7.9v.4" strokeLinecap="round" strokeWidth="2.2" />
            </svg>
          </span>
        </h2>

        <div className="divergence-reasons">
          {divergence.reasons.map((reason, i) => {
            const cited = reason.guidelineIds.map(guidelineById).filter((g): g is Guideline => Boolean(g));
            return (
              <article className="divergence-reason" key={i}>
                <span className="divergence-icon" aria-hidden="true">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.7"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    {CATEGORY_ICONS[reason.category] ?? CATEGORY_ICONS.other}
                  </svg>
                </span>
                <div className="divergence-body">
                  <h3>{reason.categoryLabel}</h3>
                  <p>{reason.explanation}</p>
                  {cited.length > 0 && (
                    <div className="divergence-sources">
                      {cited.map((g) => (
                        <span
                          key={g.id}
                          className={`divergence-source tone-${toneById.get(g.id) ?? "slate"}`}
                          title={`${g.guidelineTitle} (${g.year})`}
                        >
                          {g.organization}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <style jsx global>{`
        .divergence-panel {
          margin-top: 26px;
        }
        .divergence-h {
          display: flex;
          align-items: center;
          gap: 10px;
          margin: 0 0 16px 0;
          font-size: 22px;
          font-weight: 700;
          color: var(--ink-900);
          letter-spacing: -0.01em;
        }
        .divergence-info {
          width: 19px;
          height: 19px;
          color: var(--ink-400);
          display: inline-flex;
          cursor: help;
        }
        .divergence-info svg {
          width: 100%;
          height: 100%;
        }
        .divergence-reasons {
          display: grid;
          grid-template-columns: repeat(3, minmax(0, 1fr));
          gap: 20px;
          align-items: stretch;
        }
        .divergence-reason {
          display: flex;
          align-items: flex-start;
          gap: 17px;
          padding: 22px 24px;
          border: 1px solid #e3a83f;
          border-radius: 12px;
          background: #fdfbf4;
        }
        .divergence-icon {
          flex-shrink: 0;
          width: 50px;
          height: 50px;
          border-radius: 50%;
          background: #e0a233;
          color: #fff;
          display: inline-flex;
          align-items: center;
          justify-content: center;
        }
        .divergence-icon svg {
          width: 24px;
          height: 24px;
        }
        .divergence-body {
          min-width: 0;
        }
        .divergence-body h3 {
          margin: 0 0 8px 0;
          font-size: 18px;
          font-weight: 600;
          color: var(--ink-900);
          line-height: 1.3;
          overflow-wrap: break-word;
        }
        .divergence-body p {
          margin: 0;
          font-size: 14.5px;
          line-height: 1.6;
          color: var(--ink-600);
          overflow-wrap: break-word;
        }
        .divergence-sources {
          display: flex;
          flex-wrap: wrap;
          gap: 7px;
          margin-top: 14px;
        }
        .divergence-source {
          font-size: 12.5px;
          font-weight: 500;
          padding: 9px 14px;
          border-radius: 7px;
          max-width: 100%;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }
        .divergence-source.tone-teal {
          background: #e2efee;
          color: #2c6f69;
        }
        .divergence-source.tone-blue {
          background: #dfe7f6;
          color: #35548f;
        }
        .divergence-source.tone-violet {
          background: #eae2f4;
          color: #5b4287;
        }
        .divergence-source.tone-green {
          background: #e1f0e4;
          color: #2f6b3c;
        }
        .divergence-source.tone-rose {
          background: #f7e4e6;
          color: #8a3d4a;
        }
        .divergence-source.tone-slate {
          background: #e8ecec;
          color: #4b5c5c;
        }
        /* The amber is hard-coded rather than tokenised, so it needs its own
           dark-mode pass — cream-on-dark would otherwise glare. Follows the
           same guard pattern globals.css uses for its palettes. */
        @media (prefers-color-scheme: dark) {
          :root:not([data-theme="light"]) .divergence-reason {
            background: #2a2113;
            border-color: #7a5c22;
          }
          :root:not([data-theme="light"]) .divergence-icon {
            background: #c98f22;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-teal {
            background: #17332f;
            color: #7ecfc4;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-blue {
            background: #1a2438;
            color: #97b3e6;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-violet {
            background: #241c33;
            color: #b8a3dd;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-green {
            background: #16301c;
            color: #86c795;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-rose {
            background: #331a1e;
            color: #dda0aa;
          }
          :root:not([data-theme="light"]) .divergence-source.tone-slate {
            background: #202a2a;
            color: #a6b6b6;
          }
        }
        :root[data-theme="dark"] .divergence-reason {
          background: #2a2113;
          border-color: #7a5c22;
        }
        :root[data-theme="dark"] .divergence-icon {
          background: #c98f22;
        }
        :root[data-theme="dark"] .divergence-source.tone-teal { background: #17332f; color: #7ecfc4; }
        :root[data-theme="dark"] .divergence-source.tone-blue { background: #1a2438; color: #97b3e6; }
        :root[data-theme="dark"] .divergence-source.tone-violet { background: #241c33; color: #b8a3dd; }
        :root[data-theme="dark"] .divergence-source.tone-green { background: #16301c; color: #86c795; }
        :root[data-theme="dark"] .divergence-source.tone-rose { background: #331a1e; color: #dda0aa; }
        :root[data-theme="dark"] .divergence-source.tone-slate { background: #202a2a; color: #a6b6b6; }
        @media (max-width: 1100px) {
          .divergence-reasons { grid-template-columns: repeat(2, minmax(0, 1fr)); }
        }
        @media (max-width: 720px) {
          .divergence-reasons { grid-template-columns: 1fr; }
          .divergence-reason { padding: 18px; gap: 14px; }
          .divergence-body h3 { font-size: 17px; }
          .divergence-body p { font-size: 14px; }
        }
      `}</style>
    </>
  );
}
