import type { GradeCertaintyLevel, Guideline, GuidelineGroup } from "./types";
import { AGREE_ITEM_PATIENT_VIEWS, findAgreeItem } from "./audienceLens";

/**
 * ── Plain-language rendering for the lived-experience lens ────────────────
 *
 * This module turns a recommendation record into words a person who is not a
 * clinician can read, WITHOUT changing what it says. Everything here is a
 * restatement of a field already on the record; nothing is inferred, softened
 * or invented, and no sentence is generated by a model at render time.
 *
 * The rules below are not stylistic preferences — each one comes from the
 * patient-communication literature and each is a documented failure mode of
 * naive "simplification":
 *
 *  1. NEVER say "weak". Patients react to the word itself, not to what GRADE
 *     means by it. A weak/conditional recommendation is rendered as the GRADE
 *     patient-facing sentence: "the majority of people in this situation
 *     would want this, but many would not."
 *  2. NEVER turn a conditional recommendation into an instruction. "Suggests"
 *     is not "should". The strength sentence carries the difference.
 *  3. NEVER drop certainty to make the copy read better. Uncertainty is the
 *     thing this reader is least often told and most wants.
 *  4. Say "we don't know yet", not "there is no evidence" — the second reads
 *     as dismissal of the reader's problem.
 *  5. State plainly when patients were not asked. Whether the guideline
 *     sought the target population's views (AGREE II item 5) is one of the
 *     first things this audience looks for, and a silent omission reads as a
 *     claim that they were.
 *  6. Never answer "should I take this?" — reflect back to the trade-off and
 *     to a conversation with their own clinician.
 */

/** GRADE certainty, in words. Never shown as a bare label to this audience:
 *  symbols and one-word grades were shown to confuse readers even when a key
 *  was provided. */
export const CERTAINTY_IN_WORDS: Record<GradeCertaintyLevel, { headline: string; detail: string }> = {
  high: {
    headline: "They're confident about this",
    detail: "More research is unlikely to change this advice.",
  },
  moderate: {
    headline: "This is probably right",
    detail: "Future research could still change the picture.",
  },
  low: {
    headline: "They're not sure",
    detail: "The research so far is limited or the results are mixed.",
  },
  low_very_low: {
    headline: "They're not sure",
    detail:
      "The research behind this is limited, and for some parts of it there is very little reliable research at all.",
  },
  very_low: {
    headline: "We don't really know yet",
    detail: "There is very little reliable research behind this so far.",
  },
  not_reported: {
    headline: "They didn't say how sure they are",
    detail:
      "This guideline doesn't rate how certain the evidence is, so there's no way to tell from it alone how settled this advice is.",
  },
};

/** How much of this is the reader's call. The two sentences for strong and
 *  conditional recommendations are GRADE's own patient-facing formulations. */
export function strengthInWords(strength: string): {
  headline: string;
  detail: string;
  yourCall: "mostly settled" | "genuinely your call" | "not stated";
} {
  const s = (strength || "").toLowerCase();
  if (s.includes("strong")) {
    return {
      headline: "Most people would choose this",
      detail:
        "Most people in this situation would want this, and only a small number would not. It is still your decision.",
      yourCall: "mostly settled",
    };
  }
  if (s.includes("weak") || s.includes("conditional")) {
    return {
      headline: "This one is genuinely your call",
      detail:
        "The majority of people in this situation would want this, but many would not. Reasonable people make different choices here, and what matters most to you is what should decide it.",
      yourCall: "genuinely your call",
    };
  }
  return {
    headline: "How firm this is wasn't stated",
    detail:
      "This guideline doesn't say how strongly it holds this view, so treat it as something to discuss rather than something settled.",
    yourCall: "not stated",
  };
}

/** The recommendation's direction, said plainly and without overstating it. */
export function directionInWords(rec: Guideline): { headline: string; detail: string } {
  switch (rec.direction) {
    case "for":
      return {
        headline: "This is something they suggest doing",
        detail: "The guideline is in favour of using this in the situation it describes.",
      };
    case "against":
      return {
        headline: "This is something they suggest not doing",
        detail:
          "The guideline advises against this for now. That is not the same as “never” — it means that, on what is known today, they think the downsides outweigh the benefits.",
      };
    default:
      return {
        headline: "They couldn't reach a clear answer",
        detail:
          "The guideline stops short of advising for or against this, usually because the research isn't there yet. That's an honest “we don't know yet”, not a hidden no.",
      };
  }
}

/** Whether the guideline sought the views of the people it is about
 *  (AGREE II Domain 2, item 5). Rendered as a plain answer either way —
 *  silence here would read as a yes. */
export function patientInvolvement(group: GuidelineGroup): {
  answered: boolean;
  score: number | null;
  headline: string;
  detail: string;
  /** The appraiser's own note, verbatim. Kept separate from `detail` and
   *  shown behind a disclosure, because appraisal prose is written for
   *  methodologists — it says things like "the recommendation's weak
   *  strength", which is exactly the vocabulary this lens exists to avoid
   *  putting in front of a reader unprepared for it. Available, not hidden. */
  appraisalNote: string | null;
} {
  const item = findAgreeItem(group.agree, AGREE_ITEM_PATIENT_VIEWS);
  if (!item) {
    return {
      answered: false,
      score: null,
      headline: "We can't tell whether patients were asked",
      detail: "This guideline hasn't been checked on that point yet.",
      appraisalNote: null,
    };
  }
  if (item.score >= 6) {
    return {
      answered: true,
      score: item.score,
      headline: "Yes — people's views were sought and used",
      detail:
        "The people who wrote this guideline asked patients, carers or the public what mattered to them, and used the answers.",
      appraisalNote: item.appraisal,
    };
  }
  if (item.score >= 4) {
    return {
      answered: true,
      score: item.score,
      headline: "Partly — people's views were sought, but lightly",
      detail:
        "There was some effort to find out what patients and carers wanted, but not much detail on how it was done or what difference it made.",
      appraisalNote: item.appraisal,
    };
  }
  return {
    answered: true,
    score: item.score,
    headline: "No — people's views don't appear to have been sought",
    detail:
      "Nothing in this guideline shows that patients, carers or the public were asked what mattered to them. That is worth knowing when you read what it advises.",
    appraisalNote: item.appraisal,
  };
}

/** Who wrote it and who paid for it — the provenance this audience uses in
 *  place of a disclaimer, drawn from AGREE II Domain 6. */
export function provenance(group: GuidelineGroup): {
  organization: string;
  year: number;
  fundingScore: number | null;
  fundingNote: string | null;
  interestsScore: number | null;
  interestsNote: string | null;
} {
  const funding = findAgreeItem(group.agree, 22);
  const interests = findAgreeItem(group.agree, 23);
  return {
    organization: group.organization,
    year: group.year,
    fundingScore: funding?.score ?? null,
    fundingNote: funding?.appraisal ?? null,
    interestsScore: interests?.score ?? null,
    interestsNote: interests?.appraisal ?? null,
  };
}

/** Questions the reader could take to their own clinician. Built from the
 *  record's own uncertainty, not from a generic list: a conditional
 *  recommendation, low certainty, and an unstudied population each add the
 *  question they actually raise. */
export function questionsToAsk(rec: Guideline, group: GuidelineGroup): string[] {
  const qs: string[] = [];
  const strength = strengthInWords(rec.strength);
  if (strength.yourCall === "genuinely your call") {
    qs.push("This one is a judgement call — what would you do in my situation, and why?");
  }
  if (
    rec.gradeCertaintyLevel === "low" ||
    rec.gradeCertaintyLevel === "very_low" ||
    rec.gradeCertaintyLevel === "low_very_low"
  ) {
    qs.push("The evidence here is described as uncertain — what would change your mind either way?");
  }
  if (rec.gradeCertaintyLevel === "not_reported") {
    qs.push("This guideline doesn't say how certain the evidence is — do you know how strong it is?");
  }
  if (rec.direction === "against") {
    qs.push("If this isn't advised, what is the alternative for someone like me?");
  }
  if (rec.direction !== "for" && rec.direction !== "against") {
    qs.push("The guideline doesn't come down either way — how do you decide in practice?");
  }
  if (!rec.equity.evaluated) {
    qs.push("Does this advice apply to someone with my background and circumstances?");
  }
  const involvement = patientInvolvement(group);
  if (involvement.answered && (involvement.score ?? 7) < 4) {
    qs.push("This guideline doesn't seem to have asked patients what mattered to them — does that change how you'd use it?");
  }
  qs.push("What happens if I decide not to do this?");
  return qs.slice(0, 5);
}

/** What was actually measured, said plainly. Surrogate outcomes are called
 *  out because "they measured a test result, not how you felt" is exactly the
 *  distinction this audience is looking for and the one most often lost. */
export function outcomesInWords(rec: Guideline): { list: string[]; note: string | null } {
  const list = rec.pico.outcomes
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  if (list.length === 0) {
    return { list: [], note: "This record doesn't list what the studies measured." };
  }
  const surrogateWords = /(rate|accuracy|sensitivity|specificity|detection|yield|score|index|concordance|agreement)/i;
  const allSurrogate = list.every((o) => surrogateWords.test(o));
  return {
    list,
    note: allSurrogate
      ? "These are all measures of how well the test or tool performs — not measures of how people felt, or how long they lived. That gap matters when you're weighing this up."
      : null,
  };
}

/** The whole lived-experience rendering of one recommendation, assembled in
 *  one place so the component stays presentational. */
export interface PlainLanguageView {
  direction: { headline: string; detail: string };
  strength: { headline: string; detail: string; yourCall: string };
  certainty: { headline: string; detail: string };
  whoItIsAbout: string;
  whatItInvolves: string;
  comparedWith: string;
  outcomes: { list: string[]; note: string | null };
  involvement: ReturnType<typeof patientInvolvement>;
  provenance: ReturnType<typeof provenance>;
  questions: string[];
  /** The verbatim clinical wording, always available one click away — the
   *  plain-language version never replaces the source text. */
  verbatim: string;
}

export function toPlainLanguage(rec: Guideline, group: GuidelineGroup): PlainLanguageView {
  return {
    direction: directionInWords(rec),
    strength: strengthInWords(rec.strength),
    certainty: CERTAINTY_IN_WORDS[rec.gradeCertaintyLevel] ?? CERTAINTY_IN_WORDS.not_reported,
    whoItIsAbout: rec.pico.population || "Not stated in this record.",
    whatItInvolves: rec.pico.intervention || "Not stated in this record.",
    comparedWith: rec.pico.comparator || "Not stated in this record.",
    outcomes: outcomesInWords(rec),
    involvement: patientInvolvement(group),
    provenance: provenance(group),
    questions: questionsToAsk(rec, group),
    verbatim: rec.recommendationText,
  };
}
